backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: "portfolio/src/assets/img/uploads" # Media files will be stored in the repo under images/uploads
site_url: https://www.soler.io
logo_url: https://www.soler.io/assets/img/JointLogoNoText.png

collections:
  - name: "hero-section" # Used in routes, e.g., /admin/collections/blog
      label: "Hero Section" # Used in the UI
      files:
        - label: "Hero"
          name: "hero"
          file: "portfolio/src/assets/sections/hero-section.json"
          fields:
            - {label: "Greeting", name: "greeting", widget: "string"}
            - {label: "Introduction", name: "introduction", widget: "string"}
            - {label: "Description", name: "description", widget: "string"}
            - {label: "Dave's Expertise", name: "daveExpertise", widget: "string"}
            - {label: "Gill's Expertise", name: "gillExpertise", widget: "string"}
            
  - name: "portfolio" # Used in routes, e.g., /admin/collections/blog
    label: "Portfolio" # Used in the UI
    files:
      - label: "Projects"
        name: "projects"
        file: "portfolio/src/assets/items/project-list.json"
        fields:
          - label: "Projects"
            name: "projects"
            widget: "list"
            fields:
              - label: "Project"
                name: "project"
                widget: object
                fields:
                  - {label: "Project Name", name: "name", widget: "string"}
                  - {label: "Client Name", name: "client", widget: "string"}
                  - {label: "Project Description", name: "description", widget: "string"}
                  - {label: "Project Link", name: "link", widget: "string"}
                  - {label: "Project Thumbnail", name: "image", widget: "image"}
                  - label: "Project Type"
                    name: "icon"
                    widget: "select"
                    options:
                      - { label: "Website", value: "far fa-window-maximize" }
                      - { label: "Instagram", value: "fab fa-instagram" }
                      - { label: "Facebook", value: "fab fa-facebook" }
                      - {label: "Twitter", value: "fab fa-twitter"}
