backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: "assets/img/uploads" # Media files will be stored in the repo under images/uploads
site_url: https://www.soler.io
logo_url: https://www.soler.io/assets/img/JointLogoNoText.png

collections:
  - name: "project" # Used in routes, e.g., /admin/collections/blog
    label: "Project" # Used in the UI
    folder: "_projects" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Client", name: "client", widget: "string"}
      - {label: "Link", name: "link", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
      - label: "Project Type"
        name: "project-type"
        widget: "select"
        options:
          - { label: "Website", value: "far fa-window-maximize" }
          - { label: "Instagram", value: "fab fa-instagram" }
          - { label: "Facebook", value: "fab fa-facebook" }
          - {label: "Twitter", value: "fab fa-twitter"}
