backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: "assets/img/uploads" # Media files will be stored in the repo under images/uploads
site_url: https://www.soler.io
logo_url: https://www.soler.io/assets/img/JointLogoNoText.png

collections:
  - name: "items" # Used in routes, e.g., /admin/collections/blog
    label: "Items" # Used in the UI
    files:
      - label: "Project List"
        name: "project-list"
        file: "src/items/project-list.json"
        fields:
          - label: "Projects"
            name: "projects"
            widget: "list"
            fields:
              - label: "Project Card"
                name: "project-card"
                widget: object
                fields:
                  - {label: "Name", name: "name", widget: "string"}
                  - {label: "Client", name: "client", widget: "string"}
                  - {label: "Project Description", name: "body", widget: "string"}
                  - {label: "Link", name: "link", widget: "string"}
                  - {label: "Image", name: "image", widget: "image"}
                  - label: "Project Type"
                    name: "project-type"
                    widget: "select"
                    options:
                      - { label: "Website", value: "far fa-window-maximize" }
                      - { label: "Instagram", value: "fab fa-instagram" }
                      - { label: "Facebook", value: "fab fa-facebook" }
                      - {label: "Twitter", value: "fab fa-twitter"}
